export const APP_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const DIAGNOSTIC_MENU_ROUTE = '/diagnostic-menu'
export const DIAGNOSTIC_ROUTE = '/diagnostic'
