export const SET_VALUE_ITEM = 'SUBSECTION/SET_VALUE_ITEM'
export const SET_VALUE_STATE_FUNC = 'SUBSECTION/SET_VALUE_STATE_FUNC'
export const SET_SPEED_READING = 'SUBSECTION/SET_SPEED_READING'
export const SET_READING_SKILL = 'SUBSECTION/SET_READING_SKILL'