export const SET_VALUE_ITEM = 'TASKS/SET_VALUE_ITEM'
export const SET_VALUE_STATE_FUNC = 'TASKS/SET_VALUE_STATE_FUNC'
export const SET_SPEED_READING = 'TASKS/SET_SPEED_READING'
export const SET_READING_SKILL = 'TASKS/SET_READING_SKILL'